core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path('<slug:cat_name>/', views.Home.as_view(), name='home'),
    path('<slug:cat_name>/<slug:sub_cat>/', views.FilterProduct.as_view(), name='filterProduct'),
    path('about/', views.About.as_view(), name='about'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('product/<int:pk>', views.Product.as_view(), name='product'),
    path('products/', views.Products.as_view(), name='products'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
]

hexashop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
] 


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User 




class sub_cat(models.Model):
    title = models.CharField(max_length=100)
    url = models.CharField(max_length=100)


    def save(self, *args, **kwargs):
        prepare_url = self.title.replace(' ', '').replace('\'', '').lower()
        self.url = prepare_url
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class Category(models.Model):
    title = models.CharField(max_length=100, unique=True)
    sub_cat = models.ManyToManyField(sub_cat)

    def __str__(self):
        return self.title



class ProductModel(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField(max_length=1000, blank=True)
    image = models.ImageField(default = '', upload_to = 'product_images/')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    dis_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    in_stock = models.IntegerField()
    is_lattest = models.BooleanField(default=True)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE)


    def __str__(self):
        return self.name


class CartModel(models.Model):
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    

    @property
    def total (self):
        return (self.quantity * self.product.price)


    def __str__(self):
        return str(self.product)

core/views.py
from django.shortcuts import get_object_or_404, render
from django.views import View
from .models import ProductModel, CartModel, Category, sub_cat
import json


class Home(View):
    def get(self, request, *args, **kwargs):
        current_cat =  self.kwargs['cat_name']
        products = ProductModel.objects.all()
        cat = Category.objects.all()
        try:
            active_cat= Category.objects.get(title = current_cat)
            sub_category = active_cat.sub_cat.all()
        except:
            sub_category = []
            active_cat = []
        return render(request, 'index.html', {'products':products,'cat' :cat, 'sub_cat' :sub_category})

class FilterProduct(View):
    def get(self, request, *args, **kwargs):
        products = ProductModel.objects.all()

       
        return render(request, 'filter-product.html', {'products':products})


class Cart(View):
    def get(self, request, *args, **kwargs):
        try:
            if request.user:
                carts = CartModel.objects.filter(user = request.user)
        except:
            carts = []
        return render(request, 'cart.html', {'carts':carts})

    def post(self, request, *args, **kwargs):
        data = json.loads(self.request.body)
        action =data['form_type']
        cart_item =  data['product']
        cart_to_update = CartModel.objects.get(id=cart_item)
        if action == 'increase_qunatity':
            cart_to_update.quantity += 1
            cart_to_update.save()

        if action == 'decrease_qunatity':
            cart_to_update.quantity -= 1
            cart_to_update.save()

        if action == 'delete_cart':
            cart_to_update.delete()
        try:
            if request.user:
                carts = CartModel.objects.filter(user = request.user)
        except:
            carts = []
        return render(request, 'cart.html', {'carts':carts})

       
       

class About(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'about.html')

class Contact(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'contact.html')


class Product(View):
    def get(self, request,  pk, *args, **kwargs):
        product = ProductModel.objects.get(id = pk)
        return render(request, 'product.html', {'product': product})
    
    def post(self, request,  pk, *args, **kwargs):
        if self.request.POST.get('form_type') == 'add_to_cart':
            quantity = self.request.POST.get('quantity')
            product = self.request.POST.get('product')
            product_instance = get_object_or_404(ProductModel, id = product)
            CartModel.objects.get_or_create(product = product_instance, user = request.user, quantity=quantity)

        product = ProductModel.objects.get(id = pk)
        return render(request, 'product.html', {'product': product})


class Products(View):
    def get(self, request, *args, **kwargs):
        products = ProductModel.objects.all()
        return render(request, 'products.html',{'products': products})


class Checkout(View):
    def get(self, request, *args, **kwargs):
        products = ProductModel.objects.all()
        return render(request, 'products.html',{'products': products})

core/templates/cart.html
{% extends 'base.html' %}
{% block title %} <title>Hexashop - Cart</title> {% endblock title %}
{% load static %}

{% block content %}

<div class="ckeckout">
    <div class="container">
        <div class="ckeckout-top">
            <div class=" cart-items heading">
                {% if carts %}
                <h3>All Your Stuff ({{carts.count}})</h3>
                <ul class="unit my-5">
                    <li><span>Item</span></li>
                    <li><span>Product Name</span></li>		
                    <li><span>Unit Price</span></li>
                    <li><span>Quantity</span></li>
                    <li> <span>Total</span></li>
                </ul>
            {% endif %}
            <div class="in-check" >
                {% for item in carts %}
                
                    <ul class="cart-header">
                        <div data-product = '{{item.id}}' class="delete"></div>
                    </form>
                        <li class="ring-in text-left"><a href="" ><img src="{{item.product.image.url}}" class="img-responsive cart-img" alt="product-img"></a>
                        </li>
                        <li><span>{{item.product.name}}</span></li>
                        <li><span>$</span><span class='price'>{{item.product.price}}</span></li>
                        <li class='cart'>
                            <div class="c-btns">
                                <img class='plus' data-product='{{item.id}}' src="/media/up.svg" alt="up">
                                <img class='minus' data-product='{{item.id}}'  src="/media/up.svg" alt="down">
                            </div>
                            <span class='quantity'>{{item.quantity}}</span>
                        </li>
                        <li> <span>$</span> <span class='total'>{{ item.total }}</span></li>
                </ul>
                {% empty %}
                    <p style='font-size:30px;text-align:center;'>you have no item in cart</p>
                {% endfor %} 
                
                
            </div>
            </div>  
            <div class="btns text-right">
                <div class='main-border-button mb-3' >
                    <a href="{% url 'core:products' %}">Continue Shopping</a>
                </div>
                {% if carts.count > 0 %}
                       <div class='main-border-button' >
                           <a href="{% url 'core:checkout' %}">Checkout</a>
                       </div>
                 {% endif %} 
            
            </div>
         </div>
    </div>
</div>


{% endblock content %}

{% block scripts %}
<script>
    const csrftoken = '{{ csrf_token }}';
    console.log('{{request.user}}')
</script>
    <script src="{% static 'js/cart.js' %}"></script>

{% endblock scripts %}

core/templates/checkout.html
{% extends 'base.html' %}

core/templates/filter-product.html
{% extends 'base.html' %}

{% block title %} <title>Hexashop - product onlines</title> {% endblock title %}


{% block content %}


<!-- ***** might Like ***** -->
<section class="filterProduct category" >
    
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb mb-3">
                    <div class="location">
                        <span> Home > {{request.resolver_match.kwargs.cat_name}} > {{request.resolver_match.kwargs.sub_cat}} </span>

                    </div>

                    <div class="desc">
                        <span>200 items found |</span>

                        <label for="sort-by" class='font-weight-bold'>sort by</label>
                        <select name="" id="sort-by">
                            <option value="">Lowest</option>
                            <option value="">Highest</option>
                            <option value="">Discount</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="filter-menu">
                    <div class="catalog-menu">
                        <ul class="catalog-nav">
                            <li><a href="#">BRAND </a></li>
                        </ul>

                        <div class="catalog-arrow">
                            <svg fill="#fff" xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
                        </div>

                    </div>
                </div>

                <div class="filter-menu">
                    <div class="catalog-menu">
                        <ul class="catalog-nav">
                            <li><a href="#">COLOUR</a></li>
                        </ul>

                        <div class="catalog-arrow">
                            <svg fill="#fff" xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
                        </div>

                    </div>
                </div>
                <div class="filter-menu">
                    <div class="catalog-menu">
                        <ul class="catalog-nav">
                            <li><a href="#">OCCASION</a></li>
                        </ul>

                        <div class="catalog-arrow">
                            <svg fill="#fff" xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
                        </div>

                    </div>
                </div>
                <div class="filter-menu">
                    <div class="catalog-menu">
                        <ul class="catalog-nav">
                            <li><a href="#">CONDITION (PRE-LOVED)</a></li>
                        </ul>

                        <div class="catalog-arrow">
                            <svg fill="#fff" xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
                        </div>

                    </div>
                </div>
                <div class="filter-menu">
                    <div class="catalog-menu">
                        <ul class="catalog-nav">
                            <li><a href="#">PATTERN</a></li>
                        </ul>

                        <div class="catalog-arrow">
                            <svg fill="#fff" xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
                        </div>

                    </div>
                </div>
                <div class="filter-menu">
                    <div class="catalog-menu">
                        <ul class="catalog-nav">
                            <li><a href="#">STORE</a></li>
                        </ul>

                        <div class="catalog-arrow">
                            <svg fill="#fff" xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
                        </div>

                    </div>
                </div>
                <div class="filter-menu">
                    <div class="catalog-menu">
                        <ul class="catalog-nav">
                            <li><a href="#">EARTH EDIT</a></li>
                        </ul>

                        <div class="catalog-arrow">
                            <svg fill="#fff" xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
                        </div>

                    </div>
                </div>
                <div class="filter-menu">
                    <div class="catalog-menu">
                        <ul class="catalog-nav">
                            <li><a href="#">EXPRESS SHIPPING</a></li>
                        </ul>

                        <div class="catalog-arrow">
                            <svg fill="#fff" xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
                        </div>

                    </div>
                </div>
                <div class="filter-menu">
                    <div class="catalog-menu">
                        <ul class="catalog-nav">
                            <li><a href="#">Price range</a></li>
                        </ul>

                        <div class="catalog-arrow">
                            <svg fill="#fff" xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="men-item-carousel">
                    <div class="owl-filter-product-item owl-carousel">

                        {% for product  in products %}
                        {% if product.is_lattest %}
                            <div class="item">
                                    <div class="thumb">
                                        <div class="hover-content">
                                            <ul>
                                                <li><a href="{% url 'core:product' product.id %}">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12.015 7c4.751 0 8.063 3.012 9.504 4.636-1.401 1.837-4.713 5.364-9.504 5.364-4.42 0-7.93-3.536-9.478-5.407 1.493-1.647 4.817-4.593 9.478-4.593zm0-2c-7.569 0-12.015 6.551-12.015 6.551s4.835 7.449 12.015 7.449c7.733 0 11.985-7.449 11.985-7.449s-4.291-6.551-11.985-6.551zm-.015 3c-2.21 0-4 1.791-4 4s1.79 4 4 4c2.209 0 4-1.791 4-4s-1.791-4-4-4zm-.004 3.999c-.564.564-1.479.564-2.044 0s-.565-1.48 0-2.044c.564-.564 1.479-.564 2.044 0s.565 1.479 0 2.044z"/></svg>
                                                </a></li>
                                                <li><a href="{% url 'core:product' product.id %}">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 .587l3.668 7.568 8.332 1.151-6.064 5.828 1.48 8.279-7.416-3.967-7.417 3.967 1.481-8.279-6.064-5.828 8.332-1.151z"/></svg>
                                                </a></li>
                                                <li><a href="{% url 'core:product' product.id %}">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M10 19.5c0 .829-.672 1.5-1.5 1.5s-1.5-.671-1.5-1.5c0-.828.672-1.5 1.5-1.5s1.5.672 1.5 1.5zm3.5-1.5c-.828 0-1.5.671-1.5 1.5s.672 1.5 1.5 1.5 1.5-.671 1.5-1.5c0-.828-.672-1.5-1.5-1.5zm1.336-5l1.977-7h-16.813l2.938 7h11.898zm4.969-10l-3.432 12h-12.597l.839 2h13.239l3.474-12h1.929l.743-2h-4.195z"/></svg>
                                                </a></li>
                                            </ul>
                                        </div>
                                        <img src="{{product.image.url}}" alt="{{product.name}}">
                                    </div>
                                    <div class="down-content">
                                        <h4>{{product.name}}</h4>
                                        <span>${{product.price}}</span>
                                        <ul class="stars">
                                            <li><i class="fa fa-star"></i></li>
                                            <li><i class="fa fa-star"></i></li>
                                            <li><i class="fa fa-star"></i></li>
                                            <li><i class="fa fa-star"></i></li>
                                            <li><i class="fa fa-star"></i></li>
                                        </ul>
                                    </div>
                                </div>
                        
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ***** might Like Ends ***** -->



<!-- ***** Subscribe Area Starts ***** -->
<div class="subscribe">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="section-heading">
                    <h2>By Subscribing To Our Newsletter You Can Get 30% Off</h2>
                    <span>Details to details is what makes Hexashop different from the other themes.</span>
                </div>
                <form id="subscribe" action="" method="get">
                    <div class="row">
                      <div class="col-lg-5">
                        <fieldset>
                          <input name="name" type="text" id="name" placeholder="Your Name" required="">
                        </fieldset>
                      </div>
                      <div class="col-lg-5">
                        <fieldset>
                          <input name="email" type="text" id="email" pattern="[^ @]*@[^ @]*" placeholder="Your Email Address" required="">
                        </fieldset>
                      </div>
                      <div class="col-lg-2">
                        <fieldset>
                          <button type="submit" id="form-submit" class="main-dark-button"><i class="fa fa-paper-plane"></i></button>
                        </fieldset>
                      </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-4">
                <div class="row">
                    <div class="col-6">
                        <ul>
                            <li>Store Location:<br><span>Sunny Isles Beach, FL 33160, United States</span></li>
                            <li>Phone:<br><span>010-020-0340</span></li>
                            <li>Office Location:<br><span>North Miami Beach</span></li>
                        </ul>
                    </div>
                    <div class="col-6">
                        <ul>
                            <li>Work Hours:<br><span>07:30 AM - 9:30 PM Daily</span></li>
                            <li>Email:<br><span>info@company.com</span></li>
                            <li>Social Media:<br><span><a href="#">Facebook</a>, <a href="#">Instagram</a>, <a href="#">Behance</a>, <a href="#">Linkedin</a></span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ***** Subscribe Area Ends ***** -->


{% endblock content %}

core/templates/product.html
{% extends 'base.html' %}

{% block title %} <title>Hexashop - Product</title> {% endblock title %}

{% block content %}

    <!-- ***** Main Banner Area Start ***** -->
    <div class="page-heading" id="top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner-content">
                        <h2>Product Page</h2>
                        <span>Awesome &amp; Creative HTML CSS layout by TemplateMo</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->


    <!-- ***** Product Area Starts ***** -->
    <section class="section" id="product">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                <div class="left-images">
                    <img src="{{product.image.url}}" alt="">
                    <img src="{{product.image.url}}" alt="">
                </div>
            </div>
            <div class="col-lg-4">
                <div class="right-content">
                    <h4>{{product.name}}</h4>
                    <span class="price">${{product.price}}</span>
                    <ul class="stars">
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                    </ul>
                    <span>{{product.desc}}</span>
                    <div class="quote">
                        <i class="fa fa-quote-left"></i><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiuski smod.</p>
                    </div>
                    <div class="quantity-content">
                        <div class="left-content">
                            <h6>No. of Orders</h6>
                        </div>
                        <div class="right-content">
                            <div class="quantity buttons_added">
                                <input type="button" value="-" class="minus"><input type="number" step="1" min="1" max="" name="quantity" value="1" title="Qty" class="input-text qty text" size="4" pattern="" inputmode=""><input type="button" value="+" class="plus">
                            </div>
                        </div>
                    </div>
                    <div class="total">
                        <h4>Total: ${{product.price}}</h4>
                        <form method="post">
                            {% csrf_token %}
                                <input type="hidden" value="add_to_cart" name="form_type" >
                                <input type="hidden" value="1" name='quantity'>
                                <input type="hidden" value="{{product.id}}" name='product'>
                                <button type='submit' class="main-border-button"><a >Add To Cart</a></button>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </section>
    <!-- ***** Product Area Ends ***** -->

{% endblock content %}

templates/header.html
{% load static %}
<!-- ***** Header Area Start ***** -->
<header class="header-area header-sticky">
    <div class="top-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="/" class="logo">
                            <span>HEXASHOP</span>
                        </a>
                        <!-- ***** Logo End ***** -->
                        

                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            {% for item in cat %}
                                {% if item.title == 'h&l' %}
                                    <li><a data-link='home-living' href="{% url 'core:home' 'home-living' %}">Home & Living</a></li>
                                    {% else %}
                                    <li><a data-link='{{item.title}}' href="{% url 'core:home' item %}">{{item}}</a></li>
                                {% endif %}
                            {% endfor %}
                            
                        </ul>      

                        <!-- ***** Search Start ***** -->
                        <div class="search">
                            <Input placeholder="Search Here"></Input>

                            <div class="icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="24" viewBox="0 0 24 24"><path d="M23.809 21.646l-6.205-6.205c1.167-1.605 1.857-3.579 1.857-5.711 0-5.365-4.365-9.73-9.731-9.73-5.365 0-9.73 4.365-9.73 9.73 0 5.366 4.365 9.73 9.73 9.73 2.034 0 3.923-.627 5.487-1.698l6.238 6.238 2.354-2.354zm-20.955-11.916c0-3.792 3.085-6.877 6.877-6.877s6.877 3.085 6.877 6.877-3.085 6.877-6.877 6.877c-3.793 0-6.877-3.085-6.877-6.877z"/></svg>
                            </div>
                        </div>
                        <!-- ***** Search End ***** -->
                        
                        <ul class="nav icon justify-content-end">
                            <li class="scroll-to-section">
                                <a data-link='products' href="{% url 'core:products' %}">
                                    <svg fill='#fff' xmlns="http://www.w3.org/2000/svg" width="20" height="24" viewBox="0 0 24 24"><path d="M12 2c2.757 0 5 2.243 5 5.001 0 2.756-2.243 5-5 5s-5-2.244-5-5c0-2.758 2.243-5.001 5-5.001zm0-2c-3.866 0-7 3.134-7 7.001 0 3.865 3.134 7 7 7s7-3.135 7-7c0-3.867-3.134-7.001-7-7.001zm6.369 13.353c-.497.498-1.057.931-1.658 1.302 2.872 1.874 4.378 5.083 4.972 7.346h-19.387c.572-2.29 2.058-5.503 4.973-7.358-.603-.374-1.162-.811-1.658-1.312-4.258 3.072-5.611 8.506-5.611 10.669h24c0-2.142-1.44-7.557-5.631-10.647z"/></svg>
                                </a>
                                <div class="account-wrapper">
                                    <div class="account-header">
                                        <h2>Welcome</h2>
                                    </div>
                                    <ul class="sub-menu">
                                        <li>
                                            <a href="#">Login</a>
                                        </li>
                                        <li>
                                            <a href="#">Register</a>
                                        </li>
                                        <li>
                                            <a href="#">Track My Orders</a>
                                        </li>
                                        <li>
                                            <a href="#">Help</a>
                                        </li>
                                    </ul>
                                    <div class="account-bottom">
                                        <span>Community Influencer Program</span>
                                    </div>
                                </div>
                            </li>
                            <li >
                                <a data-link='cart' href="{% url 'core:cart' %}">
                                    <svg fill='#fff' xmlns="http://www.w3.org/2000/svg" width="20" height="24" viewBox="0 0 24 24"><path d="M4.558 7l4.701-4.702c.199-.198.46-.298.721-.298.613 0 1.02.505 1.02 1.029 0 .25-.092.504-.299.711l-3.26 3.26h-2.883zm12.001 0h2.883l-4.701-4.702c-.199-.198-.46-.298-.721-.298-.613 0-1.02.505-1.02 1.029 0 .25.092.504.299.711l3.26 3.26zm3.703 4l-.016.041-3.598 8.959h-9.296l-3.597-8.961-.016-.039h16.523zm3.738-2h-24v2h.643c.534 0 1.021.304 1.256.784l4.101 10.216h12l4.102-10.214c.233-.481.722-.786 1.256-.786h.642v-2z"/></svg>
                                </a>

                                <div class="cart-info">
                                    <span>0</span>
                                </div>
                            </li>
                        </ul>
                        
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </div>

    {% if sub_cat %}
        <div class="bottom-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <nav class="main-nav">
                            <!-- ***** Menu Start ***** -->
                            <ul class="nav">
                                {% for item in sub_cat %}
                                    <li><a href="/{{request.resolver_match.kwargs.cat_name}}/{{item.url}}/">{{item.title}}</a></li>
                                {% endfor %}
                            </ul>        
                        </nav>
                    </div>
                </div>
            </div>

        </div>
    
    {% endif %}


    
    <script>
        const current_url = '{{request.resolver_match.kwargs.cat_name}}'
        const nav_link = document.querySelectorAll('.top-header .nav li a')
        
        nav_link.forEach(element =>{
            if (element.getAttribute('data-link') == current_url){
                element.classList.add('active')
            }
        })
      </script>
  
</header>
<!-- ***** Header Area End ***** -->